version: "3"
services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: poeaa
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
